name: 'Setup Node.js Test Environment'
description: 'Sets up Node.js environment with caching and installs dependencies for testing'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  cache-dependency-path:
    description: 'Path to package-lock.json or yarn.lock file'
    required: false
    default: 'package-lock.json'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Whether dependencies were restored from cache'
    value: ${{ steps.cache-deps.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Cache node modules
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: inputs.install-dependencies == 'true' && steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Verify installation
      shell: bash
      run: |
        node --version
        npm --version
        echo "Dependencies installed successfully"
