name: 'Setup MongoDB for Testing'
description: 'Starts MongoDB service and optionally seeds the database'
inputs:
  mongodb-version:
    description: 'MongoDB version to use'
    required: false
    default: '6.0'
  mongodb-port:
    description: 'Port to run MongoDB on'
    required: false
    default: '27017'
  database-name:
    description: 'Name of the test database'
    required: false
    default: 'blogservice-testdb'
  seed-database:
    description: 'Whether to seed the database with test data'
    required: false
    default: 'false'
  seed-script:
    description: 'Path to seed script'
    required: false
    default: 'seed.js'
outputs:
  mongodb-uri:
    description: 'MongoDB connection URI'
    value: ${{ steps.setup.outputs.mongodb-uri }}
runs:
  using: 'composite'
  steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ inputs.mongodb-version }}
        mongodb-port: ${{ inputs.mongodb-port }}
        mongodb-db: ${{ inputs.database-name }}

    - name: Wait for MongoDB
      shell: bash
      run: |
        echo "Waiting for MongoDB to be ready..."
        timeout 60 bash -c 'until nc -z localhost ${{ inputs.mongodb-port }}; do sleep 1; done'
        echo "MongoDB is ready!"

    - name: Setup environment variables
      id: setup
      shell: bash
      run: |
        MONGODB_URI="mongodb://localhost:${{ inputs.mongodb-port }}/${{ inputs.database-name }}"
        echo "mongodb-uri=$MONGODB_URI" >> $GITHUB_OUTPUT
        echo "TEST_MONGO_URL=$MONGODB_URI" >> $GITHUB_ENV
        echo "MONGO_URL=$MONGODB_URI" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV
        echo "MongoDB URI: $MONGODB_URI"

    - name: Seed database
      if: inputs.seed-database == 'true'
      shell: bash
      run: |
        if [ -f "${{ inputs.seed-script }}" ]; then
          echo "Seeding database with ${{ inputs.seed-script }}"
          node ${{ inputs.seed-script }}
        else
          echo "Seed script not found: ${{ inputs.seed-script }}"
        fi
