name: 'Integration Test Development'

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag to test'
        required: false
        default: 'latest'

env:
  NODE_VERSION: '18'
  SECRET_KEY: 'test-secret-key'
  PORT: 3003
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  integration-test-dev:
    name: 'Run Integration Tests'
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      blog-service:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image-tag || 'latest' }}
        env:
          NODE_ENV: test
          SECRET_KEY: test-secret-key
          PORT: 3003
          MONGO_URL: mongodb://root:example@mongodb:27017/blogservice-testdb?authSource=admin
        ports:
          - 3003:3003
        options: >-
          --health-cmd "curl -f http://localhost:3003/api/ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for services to be ready
        run: |
          echo "Waiting for blog service to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:3003/api/ping; do sleep 2; done'
          echo "✅ Blog service is ready!"

      - name: Run integration tests
        env:
          API_BASE_URL: http://localhost:3003
          NODE_ENV: test
        run: npm run test:integration

      - name: Upload integration test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results-dev
          path: |
            test-results-integration/
          retention-days: 7
